services:
  mysql:
    image: mysql:8.0
    container_name: sistema-escoteiro-mysql
    environment:
      MYSQL_ROOT_PASSWORD: senhaRoot
      MYSQL_DATABASE: bcd
      MYSQL_USER: aluno
      MYSQL_PASSWORD: aluno
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


volumes:
  mysql_data:
    driver: local

networks:
  default:
    name: sistema-escoteiro-network